version: '2'
services:
  tests:
      build: .
      image: juanluisbaptiste/network-tests
      container_name: network-tests
      volumes:
        - $PWD:/code
        - $PWD/test_results:/test_results
      environment:
        - TEST_COUNT=1
      # links:
  #     - postfix
      # external_links:
      # - ctecsas-base/postfix:postfix
      # env_file:
      command: bash
      tty: true
      stdin_open: true
      cap_add:
        - NET_ADMIN
